version: '3'
services:
  php:
    build: 
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - .xdebug/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    ports:
      - 8080:80
    command: php -S 0.0.0.0:80 -t /var/www/html
